# add your desired knowledge graph components here

person:
  is_a: individual organism
  represented_as: node
  input_label: person

club:
  is_a: event # until finding something better
  represented_as: node
  input_label: club

timeslot:
  is_a: time
  represented_as: node
  input_label: timeslot

attends:
  is_a: association
  represented_as: edge
  use_id: false
  input_label: attends