name: Tests

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: scheduling

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry --version
        poetry config virtualenvs.create false

    - name: Install Dependencies
      run: poetry install

    - name: Run Script
      env:
        BIOCYPHER_GITHUB_PROJECT_TOKEN: ${{ secrets.BIOCYPHER_GITHUB_PROJECT_TOKEN }}
      run: poetry run python calculate_schedule.py

    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "slobentanzer@users.noreply.github.com"
      git add README.md
      git commit -m "Update README.md"
      git push